# Generated by Django 4.2.28 on 2026-02-16 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=120)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('num_serie', models.CharField(max_length=80)),
                ('fecha_alta', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('activo_equipo', models.BooleanField(default=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEquipo',
            fields=[
                ('id_estado_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado'), ('Mantenimiento', 'Mantenimiento')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='QRLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_login', models.CharField(max_length=120)),
                ('id_usuario', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.CharField(max_length=120)),
                ('entrada', models.CharField(max_length=60)),
                ('salida', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ubicacion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=120)),
                ('correo', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=255)),
                ('inLab', models.BooleanField(default=False)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, to='inventario.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField()),
                ('grupo_solicitud', models.CharField(max_length=80)),
                ('estado_solicitud', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Cancelada', 'Cancelada')], max_length=20)),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.PROTECT, to='inventario.equipo')),
                ('id_usuario_solicita', models.ForeignKey(db_column='id_usuario_solicita', on_delete=django.db.models.deletion.PROTECT, to='inventario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado_prestamo', models.CharField(choices=[('activo', 'activo'), ('cerrado', 'cerrado'), ('vencido', 'vencido')], max_length=10)),
                ('estado_solicitud', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Cancelada', 'Cancelada')], max_length=20)),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.PROTECT, to='inventario.equipo')),
                ('id_estado_equipo', models.ForeignKey(db_column='id_estado_equipo', on_delete=django.db.models.deletion.PROTECT, to='inventario.estadoequipo')),
                ('id_solicitud', models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.PROTECT, to='inventario.solicitud')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='inventario.usuario')),
                ('id_usuario_entrega', models.ForeignKey(db_column='id_usuario_entrega', on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_entregados', to='inventario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_mantenimiento', models.DateTimeField()),
                ('fecha_fin_mantenimiento', models.DateTimeField(blank=True, null=True)),
                ('estado_mantenimiento', models.CharField(choices=[('Activo', 'Activo'), ('Finalizado', 'Finalizado')], max_length=12)),
                ('descripcion_problema', models.CharField(max_length=255)),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.PROTECT, to='inventario.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='id_estado_equipo',
            field=models.ForeignKey(db_column='id_estado_equipo', on_delete=django.db.models.deletion.PROTECT, to='inventario.estadoequipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='id_ubicacion',
            field=models.ForeignKey(db_column='id_ubicacion', on_delete=django.db.models.deletion.PROTECT, to='inventario.ubicacion'),
        ),
    ]
